package io.github.big_sw_little_sw.folio.credential

import java.util.UUID

@JvmInline
value class CredentialId(
    val value: UUID,
)

@JvmInline
value class KeyId(
    val value: UUID,
)

/**
 * Unique per Git instance (ADR 0029): 1 to 100 characters of lowercase letters, digits and single hyphens, starting
 * and ending with a letter or digit (for example `payments-bot`). The same rules as namespace slugs.
 */
@JvmInline
value class CredentialName(
    val value: String,
) {
    init {
        if (value.length > MAX_LENGTH || !PATTERN.matches(value)) throw InvalidCredentialNameException(value)
    }

    override fun toString(): String = value

    private companion object {
        const val MAX_LENGTH = 100
        val PATTERN = Regex("[a-z0-9]+(-[a-z0-9]+)*")
    }
}

enum class CredentialStatus {
    ENABLED,

    /** Key operations and slice 5's sync refuse a disabled credential. v1 has no way back. */
    DISABLED,
}

/** A credential holds at most one key of each of `PENDING` and `ACTIVE`, and any number of `RETIRED` keys. */
enum class KeyStatus {
    /** Generated by a regeneration and waiting to be activated; not used for Git access yet. */
    PENDING,

    /** The key Git access uses. */
    ACTIVE,

    /** Replaced. Its private key is wiped; the public key and fingerprint stay for audit. */
    RETIRED,
}

/**
 * An SSH identity for one Git service instance, named in `folio.git.instances` (ADR 0016). Holds public key
 * material only: private keys leave the module solely through [CredentialKeyPairs].
 */
data class Credential(
    val id: CredentialId,
    val gitInstance: String,
    val name: CredentialName,
    val status: CredentialStatus,
    /** Oldest first. */
    val keys: List<CredentialKey>,
)

/** [publicKey] is the OpenSSH form without a comment (`ssh-ed25519 AAAA…`); [fingerprint] is `SHA256:…`. */
data class CredentialKey(
    val id: KeyId,
    val status: KeyStatus,
    val publicKey: String,
    val fingerprint: String,
)
